@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 10 07:45:04 +0330 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim bcdtest_behav -key {Behavioral:sim_1:Functional:bcdtest} -tclbatch bcdtest.tcl -protoinst "protoinst_files/Adder_4bit.protoinst" -protoinst "protoinst_files/FullAdder.protoinst" -protoinst "protoinst_files/mod11.protoinst" -protoinst "protoinst_files/bcdAdder.protoinst" -log simulate.log"
call xsim  bcdtest_behav -key {Behavioral:sim_1:Functional:bcdtest} -tclbatch bcdtest.tcl -protoinst "protoinst_files/Adder_4bit.protoinst" -protoinst "protoinst_files/FullAdder.protoinst" -protoinst "protoinst_files/mod11.protoinst" -protoinst "protoinst_files/bcdAdder.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
