@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 17 07:14:16 +0330 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Exp2_tb_behav -key {Behavioral:sim_1:Functional:Exp2_tb} -tclbatch Exp2_tb.tcl -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -protoinst "protoinst_files/JKFF.protoinst" -protoinst "protoinst_files/MSJKFF.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -log simulate.log"
call xsim  Exp2_tb_behav -key {Behavioral:sim_1:Functional:Exp2_tb} -tclbatch Exp2_tb.tcl -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -protoinst "protoinst_files/JKFF.protoinst" -protoinst "protoinst_files/MSJKFF.protoinst" -protoinst "protoinst_files/MY_NAND.protoinst" -protoinst "protoinst_files/NAND3.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
