# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/JKFF_NAND3_1_1.xci
# IP: The module: 'JKFF_NAND3_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_0_0/NAND3_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_0_0 || ORIG_REF_NAME==NAND3_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_0_1/NAND3_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_0_1 || ORIG_REF_NAME==NAND3_util_vector_logic_0_1} -quiet] -quiet

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_1_0/NAND3_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_1_0 || ORIG_REF_NAME==NAND3_util_vector_logic_1_0} -quiet] -quiet

# XDC: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'JKFF_NAND3_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/JKFF_NAND3_1_1.xci
# IP: The module: 'JKFF_NAND3_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_0_0/NAND3_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_0_0 || ORIG_REF_NAME==NAND3_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_0_1/NAND3_util_vector_logic_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_0_1 || ORIG_REF_NAME==NAND3_util_vector_logic_0_1} -quiet] -quiet

# IP: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_util_vector_logic_1_0/NAND3_util_vector_logic_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND3_util_vector_logic_1_0 || ORIG_REF_NAME==NAND3_util_vector_logic_1_0} -quiet] -quiet

# XDC: c:/dsdl/exp2/Exp2.srcs/sources_1/bd/JKFF/ip/JKFF_NAND3_1_1/src/NAND3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'JKFF_NAND3_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
